version: '3.9'
services:
  mongo:
    container_name: minichat-mongo
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    