version: '3.9'
services:
  mongo:
    container_name: minichat-mongo
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    container_name: minichat-redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis:/data

volumes:
  mongo:
  redis: