openapi: 3.0.0
info:
  title: Express API with OpenAPI
  version: 1.0.0
  description: Documentation for mini chat
  contact: 
    name: Minea
    email: hc2.minea@gmail.com
servers:
  - url: http://localhost:3000/api/v1
    description: development
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  security:
    - bearerAuth: []
paths: