module.exports = {
  ERROR_VALIDATION: 'ERROR_VALIDATION',
  ERROR_USERNAME_TAKEN: 'ERROR_USERNAME_TAKEN',
  ERROR_USER_INVALID: 'ERROR_USER_INVALID',
  ERROR_RESOURCE_NOTFOUND: 'ERROR_RESOURCE_NOTFOUND' 
}