const ChatSeverEvent = {
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  SEND_MESSAGE: 'SEND_MESSAGE',
  USER_ONLINE_STATUS: 'USER_ONLINE_STATUS',
  JOIN_ROOM_FRIEND_REQUEST: 'JOIN_ROOM_FRIEND_REQUEST',
  FRIEND_REQUEST_ACTION: 'FRIEND_REQUEST_ACTION'
}

module.exports = {
  ChatSeverEvent
}